# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 2.7
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
 - pip install -r requirements.txt
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover unit_tests "*.py" -v; fi